spring:
  application:
    name: "configserver"

  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          # search-locations: "file:///C://Users//stiwade//Documents//microservices//config"
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071



